# Generated by Django 4.2.4 on 2023-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='empty_profile.jpg', upload_to='profile_images'),
        ),
    ]
